title: Jingle Ma's Homepage
page-top-title: Jingle Ma
top-section-bg-text: Microelectronic Science and Engineering
home-subtitle: 马菁乐&ensp;|Jingle Ma&ensp;Undergraduate Student
copyright-text: '&copy; Jingle Ma 2025. All Rights Reserved.'
